In [3]:
a=3
b=4
if a <= b:
    print("b是比較大的數")
else:
    print("a是比較大的數")

b是比較大的數


In [5]:
sum=0
for count in range(1,11,1): #1 2 3 4 5 6 7 8 9 10 沒有11, step:1
    sum = sum + count 
print(sum)

55


In [6]:
sum=0
for count in range(1,11): #1 2 3 4 5 6 7 8 9 10 沒有11, step:1
    sum = sum + count 
print(sum)

55


In [7]:
mylist = "for statement"
for word in mylist :
    print (word)
else:
    print("end list")

f
o
r
 
s
t
a
t
e
m
e
n
t
end list


Numpy套件的ndarray型態element-wise的操作

In [9]:
import numpy as np 
b = np.array([1,2,3,4,5])
print(b*3)

[ 3  6  9 12 15]


In [10]:
print(type(b))
print(b.ndim)
print(b.shape)
print(b.dtype)

<class 'numpy.ndarray'>
1
(5,)
int32


In [12]:
print(np.zeros(6))
print(np.zeros((3,6)))
print(np.zeros((2,3,6)))

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [5]:
a=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(a)
b=np.array([np.arange(0,5),np.arange(5,10)])
print(b)
c=np.array(np.arange(0,10)).reshape((2,5))
print(c)            

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [2]:
import numpy as np 
my_2d_array=np.array(np.arange(0,10).reshape((2,5)))
print(my_2d_array)
print(my_2d_array[0,:1])
print(my_2d_array[1,])
print(my_2d_array[:,0])
print(my_2d_array[1,1])


[[0 1 2 3 4]
 [5 6 7 8 9]]
[0]
[5 6 7 8 9]
[0 5]
6


In [7]:
import numpy as np
groups=["Modern Web","DevOps","Cloud","Big Data","Security","自我挑戰組"]
ironman=[56,8,19,14,6,71]
groups_array=np.array(groups)
ironman_array=np.array(ironman)
print(groups_array)
print(ironman_array)

['Modern Web' 'DevOps' 'Cloud' 'Big Data' 'Security' '自我挑戰組']
[56  8 19 14  6 71]


請問大於10人的組別有哪些?

In [8]:
#用人數去篩選組別
print(ironman_array>=10)
print(groups_array[ironman_array>=10])

[ True False  True  True False  True]
['Modern Web' 'Cloud' 'Big Data' '自我挑戰組']


除了自我挑戰組之外的組別，人數為何?

In [9]:
#用組別去篩選人數
print(groups_array !="自我挑戰組")
print(ironman_array[groups_array !="自我挑戰組"])

[ True  True  True  True  True False]
[56  8 19 14  6]


ndarray空值nan無限大inf

In [10]:
nan_array=np.array([56,8,19,14,6,np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]


生成10組標準常態分配(平均為0，標準差為1的常態分配)隨機變數

In [11]:
normal_samples = np.random.normal(size=10)
print(normal_samples)

[ 1.10682994  1.24243286  0.12688528 -0.40526     0.11178619 -0.96899796
  0.7889328   0.65376645  0.08326976  0.69769204]


生成10組介於0~1之間的隨機變數

In [12]:
uniform_samples=np.random.uniform(size=10)
print(uniform_samples)

[0.22433563 0.74085867 0.88007534 0.68484224 0.18310247 0.66114414
 0.47173821 0.77848648 0.09900555 0.79454334]


# Numpy套件

In [1]:

a=[1,2,3,4,5]
print(a*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
